### ISSUE TITLE
Função pipeline

### ISSUE THREAD

**Issue by BrunoGomesCoelho** [SO-I-2017-2/segfault#1]
@monacofj 

De acordo com a descrição da função pipeline no trabalho, ela recebe uma quantidade variável de parâmetros ("cmd1, cmd2, … cmdN"), cada um dos "cmd" do tipo "const char * "/.

Poderíamos já receber um vetor com elas e a quantidade? Isso devido a uma certa dificuldade de se fazer funções com uma quantidade não definidas de variáveis em C.

**Comment by monacofj** [comment]
Oi Bruno

É fácil, veja aqui:

https://www.gnu.org/software/libc/manual/html_node/Variadic-Functions.html#Variadic-Functions



2017-11-26 20:27 GMT-02:00 Bruno Gomes Coelho <notifications@github.com>:

**Comment by monacofj** [comment]
Veja a correção no enunciado para resolver esse problema.

**Comment by BrunoGomesCoelho** [comment]
Entendi, obrigado professor! :)

**Comment by monacofj** [comment]
👍
